spring.application.name=main-service
server.port=8080

# Stats Server Integration
stats-server.url=http://localhost:9090

# H2 Configuration
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:ewm_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=main
spring.datasource.password=main

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# Reduce Hibernate logging
logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN

# Enable HTTP request logging
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Default logging level
logging.level.root=INFO

# Enable DEBUG logging for application packages
logging.level.ru.practicum.main=DEBUG