#spring.profiles.active=test
spring.application.name=main-service
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ewm-db:5432/ewm
spring.datasource.username=main
spring.datasource.password=main
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Stats ru.practicum.stats.StatsServerApplication Integration
stats-server.url=http://stats-server:9090

# Actuator
management.endpoints.web.exposure.include=health,info,metrics