spring.application.name=stats-server
server.port=9090

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:stats_test_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=stats
spring.datasource.password=stats
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# SQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect